---
spring:
  profiles: peer1
  application:
    name: SimpleConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JunjieShiChina/SpringCloudConfig.git
          search-paths: /**
      label: master
      username: me.shijunjie@outlook.com
      password: wssjj123

server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@192.168.1.7:8761/eureka/,http://eureka:eureka@192.168.1.21:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.7
...
---
spring:
  profiles: peer2
  application:
    name: SimpleConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JunjieShiChina/SpringCloudConfig.git
          search-paths: /**
      label: master
      username: me.shijunjie@outlook.com
      password: wssjj123

server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@192.168.1.7:8761/eureka/,http://eureka:eureka@192.168.1.21:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.21
... 
